[package]
name = "oag-node"
description = "Orange (OAG) のノード"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "oag-node"
path = "src/main.rs"

[dependencies]
clap.workspace = true
oag-chain.workspace = true
oag-consensus.workspace = true
oag-mempool.workspace = true
oag-miner = { workspace = true, features = ["randomx"] }
oag-pow = { workspace = true, features = ["randomx"] }
oag-primitives.workspace = true
oag-store.workspace = true
thiserror.workspace = true
