[package]
name = "oag-node"
description = "Orange (OAG) のノード"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lib]
name = "oag_node"
path = "src/lib.rs"

[[bin]]
name = "oag-node"
path = "src/main.rs"

[dependencies]
clap.workspace = true
oag-chain.workspace = true
oag-consensus.workspace = true
oag-mempool.workspace = true
oag-miner = { workspace = true, features = ["randomx"] }
oag-pow = { workspace = true, features = ["randomx"] }
oag-net = { workspace = true, features = ["tokio"] }
oag-primitives.workspace = true
oag-rpc.workspace = true
oag-store.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "net", "io-util", "macros", "sync", "time", "signal"] }
